### ISSUE TITLE
Confusing project name

### ISSUE THREAD

**Issue by mosabua** [dcendents/android-maven-gradle-plugin#19]
Hi!

I am the project manager and one of the core committers of the Android Maven Plugin. Our project has been running since 2009. I just found out about your project and was confused at first since you are using the same name.

However upon inspection I noticed that your project is a gradle plugin. Would it therefore be possible to rename your project to android-maven-gradle-plugin ? 

The confusing does not only exist in github but also with the tag used on stackoverflow.

**Comment by mosabua** [comment]
Here is the Android Maven Plugin project btw 

https://github.com/simpligility/android-maven-plugin

http://simpligility.github.io/android-maven-plugin/

There is also the sister project of the android-ndk-maven-plugin btw.

**Comment by dcendents** [comment]
Hi,

Sorry for taking the same name as your project, and with insight I should probably have put gradle in the name, but sometimes it seems so obvious you don’t realise it.

I’m sure you understand that I’m not using the same groupId as you, therefore there isn’t a clash between our projects, and since our projects have different end users I don’t think it’s a problem for them either.

The only real clash is the tag on stackoverflow, but my major concern about renaming the project at this stage is that’s it is actually getting used more and more every day, if I rename it now it will only confuse people looking for it. Also I’d have to try and relocate the artifacts in maven central and I’m not really sure if gradle handles relocation correctly.

And regarding stackoverflow, you understand that my plugin is simply an extension of the regular maven plugin in gradle to support android-library projects, so I wouldn’t expect the tag being used that much.

What I’m trying to say is that I don’t understand why it’s such a problem for you, other than being "inconvenient", and why that justifies going through the pain of renaming my project?

I’ll keep it in mind though, but in all cases I will not make a new release until it is necessary, which is dependent on gradle itself if they make a breaking change in the maven plugin.

Further to that, the maven plugin is kind of being deprecated in favor of the maven-publish plugin, which means the usefulness of this project is probably limited as well. I haven’t tried maven-publish with android libraries yet, and if necessary I might start a similar project and this time I’ll make sure to add gradle in the name ;-)

**Comment by mosabua** [comment]
We had to rename our project from maven-android-plugin to android-maven-plugin in the past due to restrictions from Maven/the ASF and we just recently switched groupId as well. Neither of these changes are that problematic. It would be nice for your users and developers and our users and developers to have your project renamed to reduce the confusion on github, stackoverflow or the Central Repository and others and in general. 

I also understand if you don't want to do the work, but I certainly would prefer if you could.

cc @johanlindquist @william-ferguson-au @Shusshu @malachid

**Comment by william-ferguson-au** [comment]
+1 to @mosabua's request. I really don't want to start fielding requests for a Gradle plugin. Especially if as you say it is gaining in popularity.

Changing the Github project name is trivial
Changing the artifactId is trivial.
There is no need (nor ability to) relocate artifacts in Maven Central.

It will help your users better conceive of your project and better differentiate it from the android-maven-plugin.
