### ISSUE TITLE
classifier breaks transitive dependencies.

### ISSUE THREAD

**Issue by bpappin** [dcendents/android-maven-gradle-plugin#50]
Apparently there is a bug where including a classifier, breaks transitive dependencies.
See: https://issues.gradle.org/browse/GRADLE-3188

I have a few libraries i'm installing to the local repo with this plugin, but only some of them create classified aar dependencies.

How do I control the which artifacts generate classifiers?

I'd actually prefer classifiers, but it makes a real mess of the builds to re-include everything each time.

**Comment by bpappin** [comment]
May be related to #11

**Comment by dcendents** [comment]
I would need more information to understand what you are trying to do, but it sounds like it might not be possible with a maven repository.

The rule of thumb in maven is 1 project/module (pom.xml) = 1 artifact (jar, aar, war, ear, etc) and a descriptor (artifact-version.pom)

Now classifiers are used to add extras around the single artifact. Common usage is to have sources and javadoc. Another one would be to have a jar for an older jdk.

for example:

```
.../library/1.0/library-1.0.jar
.../library/1.0/library-1.0-javadoc.jar
.../library/1.0/library-1.0-sources.jar
.../library/1.0/library-1.0-jdk15.jar
.../library/1.0/library-1.0.pom
```

But for all these maven classifiers, you have a single pom with a unique set of dependencies.

Gradle does not have that limitation (1 project = N artifact(s)) and android is pushing further with build variants and flavors. However if you intend to publish your aar artifacts in a maven repository, you need to be aware of the limitations of maven and build your projects with that in mind.

Maybe ivy would be more suitable, I haven't used it enough to know.

Another option would be to publish a different artifact for each build variant instead of using classifiers.
So something like this:

```
.../library-debug/1.0/library-debug-1.0.aar
.../library-debug/1.0/library-debug-1.0.pom
.../library-release/1.0/library-release-1.0.aar
.../library-release/1.0/library-release-1.0.pom
```

My plugin was always a patch over the standard maven plugin to enable it for android-library projects. So the standard maven documentation still applies if you want to find out how to publish different artifacts: https://docs.gradle.org/current/userguide/maven_plugin.html#sub:multiple_artifacts_per_project

**Comment by bpappin** [comment]
Using a variant is exactly why its being used this. You want a debug build to use all debug variants and a release to user all release variants.

In my specific example, I have a large app that is made up of many smaller apps. When i run a debug build, I need it to be debug all down the dependency tree.

Everything is build and published as expected, with a  debug and release version.

However, this particular issue was generated because of the "publishNonDefault true" option being set and me not realizing thats why I was getting the artifacts with a classifier.

Its a vital feature which should remain, but at the moment, dependency resolution is broken when a classifier is present.

That issue is not i this plugin, so I am going to close this issue.
